package com.neueda.interview.urlshortener.controller;

import com.neueda.interview.urlshortener.common.UrlUtil;
import com.neueda.interview.urlshortener.dto.ShortUrl;
import com.neueda.interview.urlshortener.error.InvalidUrlError;
import com.neueda.interview.urlshortener.dto.FullUrl;
import com.neueda.interview.urlshortener.service.UrlService;
import org.apache.commons.validator.routines.UrlValidator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.NoSuchElementException;

@RestController
public class UrlController {

    @Autowired
    UrlService urlService;

    /**
     * @param fullUrl Takes an object of FullUrl supplied in the request body
     * @param request To determine the protocol://domain:port part to form shortened url
     * @return An object of ShortUrl serialized as JSON in the response
     */
    @PostMapping("/shorten")
    public ResponseEntity<Object> saveUrl(@RequestBody FullUrl fullUrl, HttpServletRequest request) {

        // Validation checks to determine if the supplied URL is valid
        UrlValidator validator = new UrlValidator(
                new String[]{"http", "https"}
        );
        String url = fullUrl.getFullUrl();
        if (!validator.isValid(url)) {
            InvalidUrlError error = new InvalidUrlError("url", fullUrl.getFullUrl(), "Invalid URL");

            // returns a custom body with error message and bad request status code
            return ResponseEntity.badRequest().body(error);
        }
        String baseUrl = null;

        try {
            baseUrl = UrlUtil.getBaseUrl(request.getRequestURL().toString());
        } catch (MalformedURLException e) {
            throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR, "Request url is invalid", e);
        }

        // Retrieving the Shortened url and concatenating with protocol://domain:port
        ShortUrl shortUrl = urlService.getShortUrl(fullUrl);
        shortUrl.setShortUrl(baseUrl + shortUrl.getShortUrl());

        return new ResponseEntity<>(shortUrl, HttpStatus.OK);
    }

    /**
     * @param response HttpServletResponse - used to redirect to full url
     * @param shortenString Shortened string - Text is Base62 encoded generated by "/shorten" endpoint
     */
    @GetMapping("/{shortenString}")
    public void redirectToFullUrl(HttpServletResponse response, @PathVariable String shortenString) {
        try {
            FullUrl fullUrl = urlService.getFullUrl(shortenString);

            // Redirects the reponse to the full url
            response.sendRedirect(fullUrl.getFullUrl());
        } catch (NoSuchElementException e) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Url not found", e);
        } catch (IOException e) {
            throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR, "Could not redirect to the full url", e);
        }
    }

}
