package com.neueda.interview.urlshortener.service;

import com.neueda.interview.urlshortener.repository.UrlRepository;
import com.neueda.interview.urlshortener.common.ShorteningUtil;
import com.neueda.interview.urlshortener.model.UrlEntity;
import com.neueda.interview.urlshortener.dto.FullUrl;
import com.neueda.interview.urlshortener.dto.ShortUrl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class UrlService {

    private final UrlRepository urlRepository;

    @Autowired
    public UrlService(UrlRepository urlRepository) {
        this.urlRepository = urlRepository;
    }

    private UrlEntity get(Long id) {
        UrlEntity urlEntity = urlRepository.findById(id).get();
        return urlEntity;
    }

    /**
     * Uses the Base62 encoded to convert to Base10 number and fetches the corresponding record from the database
     *
     * @param shortenString Base62 encoded string
     * @return FullUrl object
     */
    public FullUrl getFullUrl(String shortenString) {
        return new FullUrl(this.get(ShorteningUtil.strToId(shortenString)).getFullUrl());
    }

    private UrlEntity save(FullUrl fullUrl) {
        return urlRepository.save(new UrlEntity(fullUrl.getFullUrl()));
    }

    /**
     * It saves the full url to database and uses the autogenerated id to convert to Base62 string
     *
     * @param fullUrl FullUrl object to be converted to shortened url
     * @return ShortUrl object
     */
    public ShortUrl getShortUrl(FullUrl fullUrl) {
        UrlEntity savedUrl = this.save(fullUrl);
        String shortUrlText = ShorteningUtil.idToStr(savedUrl.getId());
        return new ShortUrl(shortUrlText);
    }
}
